import React, { createContext, useContext, useEffect, useState } from 'react';
import { supabase } from '../lib/supabase';
import { User } from '@supabase/supabase-js';

interface AuthContextType {
  user: User | null;
  loading: boolean;
  isAdmin: boolean;
  signUp: (email: string, password: string, fullName: string, phone: string) => Promise<void>;
  signInWithPassword: (email: string, password: string) => Promise<void>;
  signInWithMagicLink: (email: string) => Promise<void>;
  signOut: () => Promise<void>;
}

const AuthContext = createContext<AuthContextType | undefined>(undefined);

export function AuthProvider({ children }: { children: React.ReactNode }) {
  const [user, setUser] = useState<User | null>(null);
  const [loading, setLoading] = useState(true);
  const [isAdmin, setIsAdmin] = useState(false);

  useEffect(() => {
    supabase.auth.getSession().then(({ data: { session } }) => {
      setUser(session?.user || null);
      if (session?.user) fetchIsAdmin(session.user.id);
      setLoading(false);
    });

    const { data: { subscription } } = supabase.auth.onAuthStateChange((_event, session) => {
      setUser(session?.user || null);
      if (session?.user) fetchIsAdmin(session.user.id);
      setLoading(false);
    });

    return () => subscription?.unsubscribe();
  }, []);

  const signUp = async (email: string, password: string, fullName: string, phone: string) => {
    // Generated by Copilot
    const { data, error } = await supabase.auth.signUp({ email, password });
    if (error) throw error;

    // Try to get user from signUp response (works when session is returned)
    const newUser = (data as any)?.user;
    if (newUser && newUser.id) {
      await supabase
        .from('customers')
        .upsert([
          { id: newUser.id, email, full_name: fullName, phone, is_admin: false },
        ], { onConflict: 'id' });
      setIsAdmin(false);
      return;
    }

    // If no user returned (email confirmation flow), listen once for auth state change
    const { data: sub } = supabase.auth.onAuthStateChange(async (_event, session) => {
      const user = session?.user;
      if (user && user.id) {
        await supabase
          .from('customers')
          .upsert([
            { id: user.id, email, full_name: fullName, phone, is_admin: false },
          ], { onConflict: 'id' });
        setIsAdmin(false);
        try {
          (sub as any)?.subscription?.unsubscribe();
        } catch (_) {}
      }
    });
  };

  const fetchIsAdmin = async (uid: string) => {
    try {
      const { data, error } = await supabase.from('customers').select('is_admin').eq('id', uid).single();
      if (!error && data) {
        const adminFlag = Boolean((data as any).is_admin);
        setIsAdmin(adminFlag);
        try {
          if (adminFlag && typeof window !== 'undefined' && typeof Notification !== 'undefined') {
            if (Notification.permission === 'default') {
              await Notification.requestPermission();
            }
          }
        } catch (_) {}
      } else {
        setIsAdmin(false);
      }
    } catch (err) {
      setIsAdmin(false);
    }
  };

  const signInWithPassword = async (email: string, password: string) => {
    const { error } = await supabase.auth.signInWithPassword({ email, password });
    if (error) throw error;
  };

  const signInWithMagicLink = async (email: string) => {
    const { error } = await supabase.auth.signInWithOtp({ email });
    if (error) throw error;
  };

  const signOut = async () => {
    const { error } = await supabase.auth.signOut();
    if (error) throw error;
  };

  return (
    <AuthContext.Provider value={{ user, loading, isAdmin, signUp, signInWithPassword, signInWithMagicLink, signOut }}>
      {children}
    </AuthContext.Provider>
  );
}

export function useAuth() {
  const context = useContext(AuthContext);
  if (context === undefined) {
    throw new Error('useAuth must be used within an AuthProvider');
  }
  return context;
}
