-- Generated by Copilot
-- Add is_admin column and make policies idempotent

BEGIN;

-- Ensure pgcrypto for gen_random_uuid is available
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Add is_admin to customers
ALTER TABLE customers
  ADD COLUMN IF NOT EXISTS is_admin boolean DEFAULT false;

-- Enable RLS on customers and allow users to insert their own profile
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can insert own profile" ON customers;
CREATE POLICY "Users can insert own profile"
  ON customers
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = id);

-- Products: admin-only writes
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Only authenticated users can write products" ON products;
DROP POLICY IF EXISTS "Only authenticated users can update products" ON products;
DROP POLICY IF EXISTS "Only authenticated users can delete products" ON products;

CREATE POLICY "Admins can insert products"
  ON products
  FOR INSERT
  TO authenticated
  WITH CHECK (
    EXISTS (SELECT 1 FROM customers WHERE id = auth.uid() AND is_admin = true)
  );

CREATE POLICY "Admins can update products"
  ON products
  FOR UPDATE
  TO authenticated
  USING (
    EXISTS (SELECT 1 FROM customers WHERE id = auth.uid() AND is_admin = true)
  )
  WITH CHECK (
    EXISTS (SELECT 1 FROM customers WHERE id = auth.uid() AND is_admin = true)
  );

CREATE POLICY "Admins can delete products"
  ON products
  FOR DELETE
  TO authenticated
  USING (
    EXISTS (SELECT 1 FROM customers WHERE id = auth.uid() AND is_admin = true)
  );

-- Orders: guest insert allowed; owner or admin can update/delete
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can create orders" ON orders;
CREATE POLICY "Anyone can create orders"
  ON orders
  FOR INSERT
  TO public
  WITH CHECK (true);

DROP POLICY IF EXISTS "Users can read own orders by phone" ON orders;
CREATE POLICY "Users can read own orders by phone"
  ON orders
  FOR SELECT
  TO public
  USING (true);

DROP POLICY IF EXISTS "Authenticated users can update orders" ON orders;
DROP POLICY IF EXISTS "Authenticated users can delete orders" ON orders;

CREATE POLICY "Order owner or admin can update orders"
  ON orders
  FOR UPDATE
  TO authenticated
  USING (
    EXISTS (SELECT 1 FROM customers WHERE id = auth.uid() AND is_admin = true)
    OR (customer_id IS NOT DISTINCT FROM auth.uid())
  )
  WITH CHECK (
    EXISTS (SELECT 1 FROM customers WHERE id = auth.uid() AND is_admin = true)
    OR (customer_id IS NOT DISTINCT FROM auth.uid())
  );

CREATE POLICY "Order owner or admin can delete orders"
  ON orders
  FOR DELETE
  TO authenticated
  USING (
    EXISTS (SELECT 1 FROM customers WHERE id = auth.uid() AND is_admin = true)
    OR (customer_id IS NOT DISTINCT FROM auth.uid())
  );

COMMIT;
